### ISSUE TITLE
檔名空白/中文字元issue

### ISSUE THREAD

**Issue by yiming330** [yiming330/pqi-istorage#1]
目前FAT32處理檔名含空白字元會出問題

**Comment by yiming330** [comment]
中文字元也無法顯示

**Comment by mylivan** [comment]
Accord to Microsoft FAT32 whitepaper.

Embedded spaces within a long name are allowed. Leading and trailing spaces in a long name are
ignored.
Leading and embedded periods are allowed in a name and are stored in the long name. Trailing
periods are ignored.
Long names are stored in long directory entries in UNICODE. UNICODE characters are 16-bit
characters. It is not be possible to store UNICODE in short directory entries since the

**Comment by yiming330** [comment]
Hi Livan, 這個問題我想了一下, 既然無法防止mac的使用者做這樣的行為, 我們是否要做個防呆? 如果讀到這樣的字串, 看是否要幫他trim? 或者是吐什麼information給James, 讓他那邊做處理. 因為這個應該會有消費者試出來客速.

**Comment by mylivan** [comment]
可以請你試一下，這種檔名插進 windows 系統中，會如何處理顯示？

**Comment by yiming330** [comment]
Confirmed fixed. Closing the issue.
